### PR TITLE
Adding a computed international value

### PR DESCRIPTION
**Pull request by LM450N**

### CODE REVIEW

**Comment by LM450N** [comment]
The tests failed because of the issue https://github.com/PolymerElements/iron-form-element-behavior/issues/8 .

**Comment by LM450N** [comment]
@notwaldorf can you take a look at this PR please ? :pray:

**Comment by notwaldorf** [comment]
@LM450N Argh, sorry about that. I started thinking about it, and was thinking that maybe `value` itself should actually hold the internationalized value. Imagine if you were using this in a form: in that case, `phoneInput.value` is what gets serialized, and you probably need the whole internationalized value in that case.

I think we need to do something like in `gold-cc-expiration-input`, where the gold element's `value` and the actual input's value aren't the same thing

**Comment by notwaldorf** [comment]
Closing this PR, as it's old and comments haven't been adressed. Please re-open when it's ready for another look!

**Comment by LM450N** [comment]
Sorry, I thought this PR was already rejected. I will commit a new version with your proposal of distinguish the element's value and the actual value.

**Comment by notwaldorf** [comment]
I'm not sure if that will make a breaking change (in which case we won't be able to merge it for a while)

**Comment by LM450N** [comment]
I have read the changes and I think my PR is too old. My bad! :snail:

**Comment by notwaldorf** [comment]
No worries!

**Comment by LM450N** [comment]
I have created a [new PR](https://github.com/PolymerElements/gold-phone-input/pull/64).

**Pull request closed without merging**
