### PR TITLE
Fixes #42

### LINKED ISSUE #42: label alignment
gold-phone-input's label is currently aligned above the local part of the number, leaving a space above the country code, so if you have a series of paper-inputs one on each line, the phone input's label can look not-aligned with the others:

http://jsbin.com/sidifu/1/edit?html,output

What do you think?

### PR DESCRIPTION
**Pull request by ktiedt**
Leverage paper-input prefix feature and remove extraneous container div.

### CODE REVIEW

**Comment by ktiedt** [comment]
The 5px margin was just an arbitrary value, I suppose it should actually end up being 40px to match the original?

**Comment by yordis** [comment]
@ktiedt is that the margin for the country code or for the label?

**Comment by ktiedt** [comment]
@yordis it is on the .country-code because it was otherwise ran together with the value and the label, basically the margin replaces the 40px spacing (which is why I suspect it will likely be asked to return to 40 for consistency with original)

**Comment by yordis** [comment]
@notwaldorf can you take a look to this one please

**Comment by notwaldorf** [comment]
@ktiedt Can you add some screenshots of what this looks like, please?

**Comment by ktiedt** [comment]
Absolutely, here is the demo page in its default state (since it shows most if not all permutations of this element)

image

**Comment by notwaldorf** [comment]
@ktiedt This is looking great in general, but I think there's some padding missing. Changes in padding kind of count as breaking changes at this point (since the element _used_ to look differently), so we should avoid them. :)

Before:
screen shot 2016-06-06 at 11 51 43 am

After:
screen shot 2016-06-06 at 11 51 47 am

**Comment by ktiedt** [comment]
Correct, I mentioned that after the fact, but wanted to wait till someone else chimed in, I'll update the PR.

**Comment by notwaldorf** [comment]
Yeah, let's keep UI parity and just make the code less terrible 😂

**Comment by ktiedt** [comment]
Updated PR with rewritten commit that syncs the visuals and removes the now extraneous .container class too.

Left is PR - Right is before
image

**Comment by notwaldorf** [comment]
🎉 Thanks so much Karl, this is awesome!

**Pull request merged**
