### PR TITLE
Tell the compiler the type of `value`

### PR DESCRIPTION
**Pull request by rictic**

### CODE REVIEW

**Comment by notwaldorf** [comment]
LGTM

**Comment by notwaldorf** [comment]
Wait, why are all of these needed? `value` comes from `PaperInputBehavior`, which has a type :(

**Comment by rictic** [comment]
The PolymerPass as currently written wants to know whether we're reassigning the type

**Comment by rictic** [comment]
It would be nice to make it smarter, but this is quick and easy for now

**Comment by notwaldorf** [comment]
Got it! Still LGTM

**Comment by rictic** [comment]
Thanks!

**Pull request merged**
